/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/compare` | `/compare`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/my/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `/my/settings`; params?: Router.UnknownInputParams; } | { pathname: `/building/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/report/qr/[buildingId]`, params: Router.UnknownInputParams & { buildingId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/compare` | `/compare`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/my/bookmarks`; params?: Router.UnknownOutputParams; } | { pathname: `/my/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/building/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/report/qr/[buildingId]`, params: Router.UnknownOutputParams & { buildingId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/compare${`?${string}` | `#${string}` | ''}` | `/compare${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my${`?${string}` | `#${string}` | ''}` | `/my${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/my/bookmarks${`?${string}` | `#${string}` | ''}` | `/my/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/compare` | `/compare`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/my/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `/my/settings`; params?: Router.UnknownInputParams; } | `/building/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/report/qr/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/building/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/report/qr/[buildingId]`, params: Router.UnknownInputParams & { buildingId: string | number; } };
    }
  }
}
